profile:
  name: "Boox-Note-Air-4C"
  display:
    screen_size: [1872, 1404]  # 10.3" at 227 PPI
    ppi: 227
    aspect_ratio: "4:3"
    physical_size: "10.3 inch"
  pdf_settings:
    page_size: "A4"
    orientation: "portrait"
    safe_margins: [36, 36, 36, 36]  # 0.5" safe area
  constraints:
    min_font_pt: 10.0
    min_stroke_pt: 0.75
    min_touch_target_pt: 44.0
    grayscale_levels: 16
    max_gray_fill_area: 0.15  # Avoid slow refresh