profile:
  name: "boox-tab-mini-c"
  display:
    screen_size: [1872, 1404]  # 7.8" Kaleido 3 color display
    ppi: 300
    aspect_ratio: "4:3"
    physical_size: "7.8 inch"
    color: true
  pdf_settings:
    page_size: "Custom"
    orientation: "landscape"
    safe_margins: [36, 36, 36, 36]
  constraints:
    min_font_pt: 8.0   # Smaller screen, smaller minimum
    min_stroke_pt: 0.5
    min_touch_target_pt: 30.0
    grayscale_levels: 16
    max_gray_fill_area: 0.2
