profile:
  name: "kobo-clara-2e"
  display:
    screen_size: [1072, 1448]  # 6" E Ink Carta 1200
    ppi: 300
    aspect_ratio: "3:4"
    physical_size: "6 inch"
    color: false
  pdf_settings:
    page_size: "Custom"
    orientation: "portrait"
    safe_margins: [24, 24, 24, 24]
  constraints:
    min_font_pt: 8.0
    min_stroke_pt: 0.5
    min_touch_target_pt: 28.0
    grayscale_levels: 16
    max_gray_fill_area: 0.2
