version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      # Database configuration (Phase 0 - SQLite with WAL mode)
      - DATABASE_URL=sqlite:///data/einkpdf.sqlite
      - DB_ECHO=false

      # Core application settings
      - APP_NAME=einkpdf
      - APP_VERSION=0.2.3
      - DEBUG=false
      - EINK_CLEANUP_TTL_DAYS=14
      - EINK_PROFILE_DIR=/app/config/profiles
      - EINK_DATA_DIR=/app/backend/data

      # Storage paths (Phase 0 - unified data directory)
      - STORAGE_DIR=/app/backend/data
      - ASSETS_DIR=/app/backend/data/assets
      - JOBS_DIR=/app/backend/data/jobs

      # JWT Authentication settings
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-secrNicIn-change-i892oduction}
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7

      # Password reset settings
      - EINK_PASSWORD_RESET_TTL_MINUTES=60
      - EINK_PASSWORD_RESET_URL=${PASSWORD_RESET_URL:-http://localhost:3000/reset-password}

      # Email settings (for password reset)
      # For development, emails will be saved to files
      - EINK_EMAIL_OUTPUT_DIR=/app/backend/data/emails
      # For production, configure SMTP:
      # - EINK_SMTP_HOST=smtp.example.com
      # - EINK_SMTP_PORT=587
      # - EINK_SMTP_USERNAME=noreply@example.com
      # - EINK_SMTP_PASSWORD=your_smtp_password
      # - EINK_SMTP_FROM=noreply@example.com
      # - EINK_SMTP_USE_TLS=true

      # PDF Generation Limits (Phase 1)
      - MAX_PDF_PAGES=1000
      - MAX_PDF_SIZE_MB=50
      - PDF_TIMEOUT_SECONDS=600

      # Image Upload Limits (Phase 1)
      - MAX_IMAGE_SIZE_BYTES=524288  # 0.5MB

      # Rate Limiting (Phase 1)
      - RATE_LIMIT_ENABLED=true
      - PDF_GENERATE_RATE_LIMIT=10/minute
      - PDF_PREVIEW_RATE_LIMIT=30/minute
      - IMAGE_UPLOAD_RATE_LIMIT=20/minute

      # CORS configuration
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173

      # Logging
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    volumes:
      # Phase 0: Unified data directory for database, assets, jobs, and user projects
      - eink_data:/app/backend/data
      - ./config/profiles:/app/config/profiles:ro
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:${BACKEND_PORT:-8000}/api

volumes:
  # Phase 0: Unified data directory for all persistent data
  eink_data: {}
