0version: "3.9"

services:
  backend:
    image: eink-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      # Core application settings
      - DEBUG=false  # Production mode - enables secure cookies for HTTPS
      - EINK_CLEANUP_TTL_DAYS=14
      - EINK_PROFILE_DIR=/app/config/profiles
      - EINK_DATA_DIR=/app/backend/data
      # - EINK_CLEANUP_MAX_TEMPLATES=500

      # JWT Authentication
      - EINK_JWT_SECRET_FILE=/app/backend/data/users/jwt_secret.txt
      - EINK_JWT_ALGORITHM=HS256
      - EINK_JWT_EXPIRES_MINUTES=43200  # 30 days

      # Password reset
      - EINK_PASSWORD_RESET_TTL_MINUTES=60
      # Frontend will be served under Traefik on the same host; use public URL if you send links in emails:
      - EINK_PASSWORD_RESET_URL=${PASSWORD_RESET_URL:-https://dokumenty.cgpsmapper.com/reset-password}

      # Email (file-based by default; switch to SMTP in production when ready)
      - EINK_EMAIL_OUTPUT_DIR=/app/backend/data/emails
      # - EINK_SMTP_HOST=smtp.example.com
      # - EINK_SMTP_PORT=587
      # - EINK_SMTP_USERNAME=noreply@example.com
      # - EINK_SMTP_PASSWORD=your_smtp_password
      # - EINK_SMTP_FROM=noreply@example.com
      # - EINK_SMTP_USE_TLS=true
    volumes:
      # Keep QNAP bind-mounts
      - /share/homes/staszek/eink/data:/app/backend/data
      - /share/homes/staszek/eink/config/profiles:/app/config/profiles:ro
    # Do NOT publish backend to the host; Traefik/front will reach it via the Docker network
    restart: unless-stopped
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  frontend:
    image: eink-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    # Optional: keep host port if you also want to reach it directly (outside Traefik)
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
    environment:
      # IMPORTANT: Same-origin API to avoid 'localhost' in the browser.
      # Your frontend web server (e.g., nginx) should proxy /api -> http://backend:8000
      - VITE_API_BASE_URL=/api
    restart: unless-stopped
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  proxy:
    external: true


