"""Initial schema for multi-user system

Revision ID: 29e8204f390a
Revises: 
Create Date: 2025-10-02 12:57:24.692377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e8204f390a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_owner_created', 'assets', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('ix_password_resets_expires', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_table('pdf_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_path', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pdf_jobs_created', 'pdf_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_pdf_jobs_owner_id'), 'pdf_jobs', ['owner_id'], unique=False)
    op.create_index('ix_pdf_jobs_owner_status', 'pdf_jobs', ['owner_id', 'status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('device_profile', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('plan_yaml', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index('ix_projects_owner_updated', 'projects', ['owner_id', 'updated_at'], unique=False)
    op.create_table('public_projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('owner_username', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('url_slug', sa.String(length=80), nullable=True),
    sa.Column('clone_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_projects_owner_id'), 'public_projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_public_projects_url_slug'), 'public_projects', ['url_slug'], unique=True)
    op.create_table('user_quotas',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('project_count', sa.Integer(), nullable=False),
    sa.Column('asset_count', sa.Integer(), nullable=False),
    sa.Column('storage_bytes', sa.Integer(), nullable=False),
    sa.Column('pdf_jobs_today', sa.Integer(), nullable=False),
    sa.Column('quota_reset_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quotas')
    op.drop_index(op.f('ix_public_projects_url_slug'), table_name='public_projects')
    op.drop_index(op.f('ix_public_projects_owner_id'), table_name='public_projects')
    op.drop_table('public_projects')
    op.drop_index('ix_projects_owner_updated', table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_pdf_jobs_owner_status', table_name='pdf_jobs')
    op.drop_index(op.f('ix_pdf_jobs_owner_id'), table_name='pdf_jobs')
    op.drop_index('ix_pdf_jobs_created', table_name='pdf_jobs')
    op.drop_table('pdf_jobs')
    op.drop_index('ix_password_resets_expires', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_index('ix_assets_owner_created', table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
